lib/chunky_remote_web/router.ex
defmodule ChunkyRemoteWeb.Router do
  use ChunkyRemoteWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChunkyRemoteWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChunkyRemoteWeb do
    pipe_through :browser

    get "/", LoginController, :new
    resources "/login", LoginController, only: [:new, :create]
    resources "/users", UserController, only: [:new, :create, :index]
    resources "/users/verify", VerifyController, only: [:new, :create]
    resources "/dashboard", DashboardController, only: [:index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChunkyRemoteWeb do
  #   pipe_through :api
  # end
end

lib/chunky_remote_web/controllers/verify_controller.ex
defmodule ChunkyRemoteWeb.VerifyController do
  use ChunkyRemoteWeb, :controller
  alias ChunkyRemote.{Account, Account.User}

  def new(conn, _params) do
    render(conn, "new.html", changeset: User.verify_changeset(%User{}, %{}))
  end

  def create(conn, %{
        "user" => %{
          "username" => username,
          "password" => password,
          "new_password" => new_password
        }
      }) do
    with {:ok, user} <- Account.get_user_by_username(username) do
      Account.verify_user(user, %{old_password: password, password: new_password})

      conn
      |> assign(:current_user, user)
      |> put_session(:user_id, user.id)
      |> put_flash(:info, "Verified user: #{user.username}")
      |> redirect(to: Routes.dashboard_path(conn, :index))
    end
  end
end

lib/chunky_remote_web/views/verify_view.ex
defmodule ChunkyRemoteWeb.VerifyView do
  use ChunkyRemoteWeb, :view
end

lib/chunky_remote_web/templates/verify/new.html.eex
<div class="p-8">
  <h1 class="text-2xl text-black font-bold">Verify Your Account</h1>

  <%= form_for @changeset, Routes.verify_path(@conn, :create), fn f -> %>
    <div>
      User Name <%= text_input f, :username, placeholder: "User Name" %>
    </div>

    <div>
      Temp Password <%= text_input f, :password, placeholder: "Temporary Password" %>
    </div>

    <div>
      New Password <%= text_input f, :new_password, placeholder: "New Password" %>
    </div>

    <%= submit "Verify User" %>
  <% end %>
</div>